version: '3.4'

services:
  mongodb:
    image: mongo:6.0.4
    volumes:
      - ~/mongors/data:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    hostname: mongodb
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - mongo-network
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u mongo -p mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: [ "--replSet", "dbrs", "--bind_ip_all" ]

networks:
  mongo-network:
    driver: bridge
