version: '3.8'

services:
  mongo1:
    container_name: mongo1
    image: mongo:6.0.4
    volumes:
      - ~/mongors/data1:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    ports:
      - 27017:27017
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0"
      ]
    links:
      - mongo2
      - mongo3
    restart: always
    networks:
      - mongors-network

  mongo2:
    container_name: mongo2
    image: mongo:6.0.4
    volumes:
      - ~/mongors/data2:/data/db
    ports:
      - 27018:27017
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0"
      ]
    restart: always
    networks:
      - mongors-network

  mongo3:
    container_name: mongo3
    image: mongo:6.0.4
    volumes:
      - ~/mongors/data3:/data/db
    ports:
      - 27019:27017
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0"
      ]
    restart: always
    networks:
      - mongors-network

networks:
  mongors-network:
    driver: bridge
